### PR TITLE
Add trb spot price to catalog

### LINKED ISSUE #370: Add TRB spot price feed
Currently the only TRB feed in telliot is a legacy query type.
For Tellor 360 we will need to add a TRB spot price feed to that conforms to the new query builder standard.

### PR DESCRIPTION
**Pull request by tallywiesenberg**
Closes #370 
### Summary

Replaces TRB legacy feed in catalog with TRB SpotPrice query/feed
### Steps Taken to QA Changes

Updated TRB median feed tests

### Checklist

This pull request is:

- [ ] A documentation error, docs update, or typographical error fix
	- No tests or issue needed
- [ ] A code fix
	- Please reference the related issue by including "Closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a bug report issue 
	- Please include tests. Fixes without tests will not be accepted unless it's related to the documentation only.
    - Please make sure docs are updated if need be
- [x] A feature implementation
	- Please reference the related issue by including "Closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a feature enhancement issue 
	- Please include tests
    - Please make sure docs updates are both thorough and easy to reproduce by somebody with limited knowledge of the feature that you are submitting

**Happy engineering!**

### CODE REVIEW

**Comment by tallywiesenberg** [comment]
submission TX: https://rinkeby.etherscan.io/tx/0x6ae74d763a8f0917df51854593f8e10f210d8fc92c2413357801022c344bad82

**Comment by tallywiesenberg** [comment]
decoded data:
```sh
(venv) m1 ➜  telliot-feed-examples (add-trb-spot) telliot-feeds query decode -qd 0x00000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000953706f745072696365000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000003747262000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000037573640000000000000000000000000000000000000000000000000000000000

Query: SpotPrice(asset='trb', currency='usd')
(venv) m1 ➜  telliot-feed-examples (add-trb-spot) telliot-feeds query decode -svb 0x000000000000000000000000000000000000000000000000e27c49886e60011c
Choose query type to decode submitted value:
[1] -- LegacyRequest
[2] -- SpotPrice
[3] -- Morphware
[4] -- GasPriceOracle
[5] -- Snapshot
[6] -- DailyVolatility
[7] -- NumericApiResponse
[8] -- DIVAProtocol
[9] -- StringQuery
[10] -- TellorRNG
[11] -- TWAP
Enter number from 1-11: 2
Your choice: SpotPrice
Decoded value: 16.32
```

**Comment by oraclown** [comment]
> submission TX: https://rinkeby.etherscan.io/tx/0x6ae74d763a8f0917df51854593f8e10f210d8fc92c2413357801022c344bad82

Awesome, thanks

**Review by oraclown — CHANGES_REQUESTED** [review]
Thanks for this @tallywiesenberg ! We should keep the legacy one in their though, so we have both. Just change it's feed name to trb usd legacy feed or something, and then the spot price one would be trb median probs.

**Comment by tallywiesenberg** [comment]
> Thanks for this @tallywiesenberg ! We should keep the legacy one in their though, so we have both. Just change it's feed name to trb usd legacy feed or something, and then the spot price one would be trb median probs.

Cool! I restored the trb/usd legacy request catalog item.

**Review by oraclown — APPROVED** [review]
Thanks sire

**Pull request merged**
