### PR TITLE
Feat/update pls feed to support puslechain mainnet & testnet

### PR DESCRIPTION
**Pull request by johnny-vu**
This changes will support to get `PLS/USD` spot price on pulsechain mainnet (chainId: 369) & testnet (chainId: 943)

### Summary

- Add pulsechain chains.
- Update `pls_usd_feed`, using `PriceAggregator` with multiple sources.
- Remove pulsechain subgraph service.
- Add test `tests/feeds/test_pls_usd_feed.py`

### Steps Taken to QA Changes

- Run the test:

```
tests/feeds/test_pls_usd_feed.py::test_pls_usd_median_feed
----------------------------------------------------------------------------------------------------------------------- live log call ------------------------------------------------------------------------------------------------------------------------
INFO     telliot_feeds.sources.price_aggregator:price_aggregator.py:91 Running median on [0.00011231, 0.00011237464510385463, 0.0001106946969326687]
INFO     telliot_feeds.sources.price_aggregator:price_aggregator.py:96 Feed Price: 0.00011231 reported at time 2023-06-09 16:32:36.502805+00:00
INFO     telliot_feeds.sources.price_aggregator:price_aggregator.py:97 Number of sources used in aggregate: 3
PASSED
```

- Submit value:

`https://scan.pulsechain.com/tx/0xee26f75be1672bbbcee33e657cd56ba017f05033634a0526fd1a75c3825a76da`

### Checklist

This pull request is:

- [x] A documentation error, docs update, or typographical error fix
	- No tests or issue needed
- [x] A code fix
	- Please reference the related issue by including "Closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a bug report issue 
	- Please include tests. Fixes without tests will not be accepted unless it's related to the documentation only.
    - Please make sure docs are updated if need be
- [x] A feature implementation
	- Please reference the related issue by including "Closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a feature enhancement issue 
	- Please include tests
    - Please make sure docs updates are both thorough and easy to reproduce by somebody with limited knowledge of the feature that you are submitting

**Happy engineering!**

### CODE REVIEW

**Comment by johnny-vu** [comment]
Hi @akremstudy, thanks for your feedback.

My apologies, I think the repo should be [multicall.py](https://github.com/banteg/multicall.py)

In my opinion, I think we can define `multicall3` address in `src/telliot_feeds/reporters/tips/__init__.py`. However, I found [this](https://github.com/tellor-io/telliot-feeds/blob/main/setup.cfg#L71).
So I also think if we just update `multicall` to new version and that would be better to optimize the source code.

What do you think?

**Comment by akremstudy** [comment]
> Hi @akremstudy, thanks for your feedback.
> 
> My apologies, I think the repo should be [multicall.py](https://github.com/banteg/multicall.py)
> 
> In my opinion, we can define `multicall3` address in `src/telliot_feeds/reporters/tips/__init__.py`. However, I found [this](https://github.com/tellor-io/telliot-feeds/blob/main/setup.cfg#L71). So I also think if we just update `multicall` to new version and that would be better to optimize the source code.
> 
> What do you think?

Yeah thats the repo you're looking for, the banteg/multicall repo, thats where you want to make a pr to add the pulsechain network.  
Updating the multicall package isn't going to make a difference until the pulsechain network is added to the multicall package but we can definitely circle back once thats the case and see if we can update the version without any issues.
In the meantime you can add the network in the __init__ file to get up and running ie,
```python
add_multicall_support(
    network="Pulsechain",
    network_id=369,
    state_override=False,
    multicall3_address="0xcA11bde05977b3631167028862bE2a173976CA11",
)
```

**Comment by johnny-vu** [comment]
@akremstudy thank you. I'm clear for now.

I've submitted new PR is [here](https://github.com/banteg/multicall.py/pull/78) and we'll see how it all goes.
Give me a few hours to update this PR according to your suggestion.

**Comment by akremstudy** [comment]
> @akremstudy thank you. I'm clear for now.
> 
> I've submitted new PR is [here](https://github.com/banteg/multicall.py/pull/78) and we'll see how it all goes. Give me a few hours to update this PR according to your suggestion.

Awesome!

**Comment by johnny-vu** [comment]
Hi @akremstudy I've done this PR, could you please take a look?

Quick question, should I wait for `telliot-core` to release a new version and update `setup.cfg` before we can merge?

**Review by akremstudy — APPROVED** [review]
Thanks @johnny-vu!

**Comment by johnny-vu** [comment]
Thanks @akremstudy!

**Pull request merged**
