### PR TITLE
added sepolia stuff

### PR DESCRIPTION
**Pull request by spuddyminer**
added sepolia again working 100% tested by reporting on sepolia and listening for tips and running tox -e style.

### CODE REVIEW

**Review by oraclown — COMMENTED** [review]
Thanks, @spuddyminer !

Looks like the [telliot-core version](https://github.com/tellor-io/telliot-feeds/blob/main/setup.cfg#L85) isn't updated. Step five of the [add-chain docs](https://tellor-io.github.io/telliot-feeds/add-chain/). I'd check the other steps to see if something else missed while you're at it.

**Comment by spuddyminer** [comment]
step 5 says: "Once you've done a new release of telliot-core, update that dependency in this package's setup.cfg to the new version."

In setup.cfg, I don't see where the version of telliot-core is specified at all. 
There's a line that says `version = attr: telliot_core.__version__` .... is it that?

**Comment by oraclown** [comment]
> telliot-core version

I linked the line that needs to be changed above (:

**Comment by spuddyminer** [comment]
yea found it, it helped to look in telliot-feeds

**Comment by oraclown** [comment]
Looks like you updated the `telliot-feeds` version elsewhere, going to merge this

**Pull request merged**
