### PR TITLE
Add native token support for Optimism and Arbitrum

### PR DESCRIPTION
**Pull request by akremstudy**
### Summary

Chain ids for Arbitrum (One+Goerli) and Optimisim(Mainnet+Goerli) added to:
- constants.py for native_token_support
- reporter_autopay_utils.py for autopay support (also checked if multicall is deployed, [for Optimism](https://goerli-optimism.etherscan.io/address/0x3251838bd813fdf6a97D32781e011cce8D225d59#code) and [for Arbitrum](https://goerli.arbiscan.io/address/0xd5f1Cc896542C111c7Aa7D7fae2C3D654f34b927)

To submit on arbitrum, the gas_limit has to be increased for a successful submission more than on other chains, I think for the way the gas is calculated on that chain. Here is the command I used to submit a value ```telliot report -a g-arbitrum-acct -p YOLO -mnb 0 -rf -wp 20 -gl 3500000  ```
- [Optimisim-goerli txn](https://goerli-optimism.etherscan.io//tx/0x899013a3ec281f8f6669ae2e5b0fd7ea7aab607e119d2c52b2eaf09050653a6c)
- [Arbitrum-goerli txn](https://goerli.arbiscan.io//tx/0x9064ac905b1727bf67daa3dd15ebc6b239370b5bf8a952964134c0d1906aa581)

Other changes:
* Removed hardcoded gas limit for depositing stake and used the available self.gas_limit var.

* A ZerodivisionError happened due to stakeAmount being zero for the playground and would break things when calculating reportingLock so added a try/except.

* Renamed the param for legacy_gas_station function to match the upcoming change on telliot-core. 
Submisson txns to other chains to check if they were affected
- [Chiado](https://blockscout.com/gnosis/chiado/tx/0xb8328ba68de44f4092d185d64dfd8ee3c3dd845a2319a0057dddd16e00d1fddf)
- [Goerli](https://goerli.etherscan.io/tx/0x94947bf26e8b1aded57d036e43660ab90fd13cec5eaec01a6ad1f894e13a0b1c)
- [Mumbai](https://mumbai.polygonscan.com/tx/0x9de70761692c21a8959b609c549664e34ec731500cadad09d9c2aaf638ab9280)
### Checklist

This pull request is:

- [ ] A documentation error, docs update, or typographical error fix
	- No tests or issue needed
- [x] A code fix
	- Please reference the related issue by including "Closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a bug report issue 
	- Please include tests. Fixes without tests will not be accepted unless it's related to the documentation only.
    - Please make sure docs are updated if need be
- [x] A feature implementation
	- Please reference the related issue by including "Closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a feature enhancement issue 
	- Please include tests
    - Please make sure docs updates are both thorough and easy to reproduce by somebody with limited knowledge of the feature that you are submitting

**Happy engineering!**

### CODE REVIEW

**Review by oraclown — APPROVED** [review]
Thanks @akremstudy , looks good. Goign to to a `telliot-core` release b4 merging to see if I can fix the typing thing in flex:
```py
async def fetch_gas_price(self, speed: Optional[str] = None) -> Optional[int]:
        """Fetch estimated gas prices.
        Expected to return gas price in gwei."""
        return await legacy_gas_station(chain_id=self.chain_id, speed_parse_lis=speed)  # type: ignore
```

**Comment by oraclown** [comment]
> 

It doesn't fix this, so leaving how you have it

**Comment by akremstudy** [comment]
> Just had this error pop up while using this branch
> 
> ```
> ERROR   | telliot_core.gas.legacy_gas | Unable to parse gas price from gasstation: ['speeds', 2, 'gasPrice']
> WARNING | telliot_feeds.reporters.tellor_flex | unable to fetch gas price from api
> ERROR   | telliot_core | Exception occurred in telliot-core app
> ERROR   | telliot_core | <class 'AttributeError'>
> ERROR   | telliot_core | 'NoneType' object has no attribute 'ok'
> ERROR   | telliot_core | ['  File "/home/ubuntu/op/telliot-feeds/src/telliot_feeds/cli/commands/report.py", line 496, in report\n    await reporter.report()\n', '  File "/home/ubuntu/op/telliot-feeds/src/telliot_feeds/reporters/interval.py", line 465, in report\n    _, _ = await self.report_once()\n', '  File "/home/ubuntu/op/telliot-feeds/src/telliot_feeds/reporters/interval.py", line 342, in report_once\n    if not status.ok:\n']
> Traceback (most recent call last):
>   File "/home/ubuntu/op/tenv/bin/telliot", line 8, in <module>
>     sys.exit(main())
>   File "/home/ubuntu/op/tenv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/ubuntu/op/tenv/lib/python3.9/site-packages/click/core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "/home/ubuntu/op/tenv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/ubuntu/op/tenv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/ubuntu/op/tenv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "/home/ubuntu/op/tenv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/home/ubuntu/op/telliot-core/src/telliot_core/cli/utils.py", line 18, in wrapper
>     return asyncio.run(f(*args, **kwargs))
>   File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
>     return future.result()
>   File "/home/ubuntu/op/telliot-feeds/src/telliot_feeds/cli/commands/report.py", line 496, in report
>     await reporter.report()
>   File "/home/ubuntu/op/telliot-feeds/src/telliot_feeds/reporters/interval.py", line 465, in report
>     _, _ = await self.report_once()
>   File "/home/ubuntu/op/telliot-feeds/src/telliot_feeds/reporters/interval.py", line 342, in report_once
>     if not status.ok:
> AttributeError: 'NoneType' object has no attribute 'ok'
> ```

@spuddyminer what chain was being reported here?

**Comment by oraclown** [comment]
> Just had this error pop up while using this branch
> 
> ```
> ERROR   | telliot_core.gas.legacy_gas | Unable to parse gas price from gasstation: ['speeds', 2, 'gasPrice']
> WARNING | telliot_feeds.reporters.tellor_flex | unable to fetch gas price from api
> ERROR   | telliot_core | Exception occurred in telliot-core app
> ERROR   | telliot_core | <class 'AttributeError'>
> ERROR   | telliot_core | 'NoneType' object has no attribute 'ok'
> ERROR   | telliot_core | ['  File "/home/ubuntu/op/telliot-feeds/src/telliot_feeds/cli/commands/report.py", line 496, in report\n    await reporter.report()\n', '  File "/home/ubuntu/op/telliot-feeds/src/telliot_feeds/reporters/interval.py", line 465, in report\n    _, _ = await self.report_once()\n', '  File "/home/ubuntu/op/telliot-feeds/src/telliot_feeds/reporters/interval.py", line 342, in report_once\n    if not status.ok:\n']
> Traceback (most recent call last):
>   File "/home/ubuntu/op/tenv/bin/telliot", line 8, in <module>
>     sys.exit(main())
>   File "/home/ubuntu/op/tenv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/ubuntu/op/tenv/lib/python3.9/site-packages/click/core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "/home/ubuntu/op/tenv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/ubuntu/op/tenv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/ubuntu/op/tenv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "/home/ubuntu/op/tenv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/home/ubuntu/op/telliot-core/src/telliot_core/cli/utils.py", line 18, in wrapper
>     return asyncio.run(f(*args, **kwargs))
>   File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
>     return future.result()
>   File "/home/ubuntu/op/telliot-feeds/src/telliot_feeds/cli/commands/report.py", line 496, in report
>     await reporter.report()
>   File "/home/ubuntu/op/telliot-feeds/src/telliot_feeds/reporters/interval.py", line 465, in report
>     _, _ = await self.report_once()
>   File "/home/ubuntu/op/telliot-feeds/src/telliot_feeds/reporters/interval.py", line 342, in report_once
>     if not status.ok:
> AttributeError: 'NoneType' object has no attribute 'ok'
> ```

cmd to reproduce (on opt mainnet): `telliot report -a account -qt btc-usd-spot -p YOLO -wp 30`

**Comment by akremstudy** [comment]
> > Just had this error pop up while using this branch
> > ```
> > ERROR   | telliot_core.gas.legacy_gas | Unable to parse gas price from gasstation: ['speeds', 2, 'gasPrice']
> > WARNING | telliot_feeds.reporters.tellor_flex | unable to fetch gas price from api
> > ERROR   | telliot_core | Exception occurred in telliot-core app
> > ERROR   | telliot_core | <class 'AttributeError'>
> > ERROR   | telliot_core | 'NoneType' object has no attribute 'ok'
> > ERROR   | telliot_core | ['  File "/home/ubuntu/op/telliot-feeds/src/telliot_feeds/cli/commands/report.py", line 496, in report\n    await reporter.report()\n', '  File "/home/ubuntu/op/telliot-feeds/src/telliot_feeds/reporters/interval.py", line 465, in report\n    _, _ = await self.report_once()\n', '  File "/home/ubuntu/op/telliot-feeds/src/telliot_feeds/reporters/interval.py", line 342, in report_once\n    if not status.ok:\n']
> > Traceback (most recent call last):
> >   File "/home/ubuntu/op/tenv/bin/telliot", line 8, in <module>
> >     sys.exit(main())
> >   File "/home/ubuntu/op/tenv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
> >     return self.main(*args, **kwargs)
> >   File "/home/ubuntu/op/tenv/lib/python3.9/site-packages/click/core.py", line 1055, in main
> >     rv = self.invoke(ctx)
> >   File "/home/ubuntu/op/tenv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
> >     return _process_result(sub_ctx.command.invoke(sub_ctx))
> >   File "/home/ubuntu/op/tenv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
> >     return ctx.invoke(self.callback, **ctx.params)
> >   File "/home/ubuntu/op/tenv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
> >     return __callback(*args, **kwargs)
> >   File "/home/ubuntu/op/tenv/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
> >     return f(get_current_context(), *args, **kwargs)
> >   File "/home/ubuntu/op/telliot-core/src/telliot_core/cli/utils.py", line 18, in wrapper
> >     return asyncio.run(f(*args, **kwargs))
> >   File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
> >     return loop.run_until_complete(main)
> >   File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
> >     return future.result()
> >   File "/home/ubuntu/op/telliot-feeds/src/telliot_feeds/cli/commands/report.py", line 496, in report
> >     await reporter.report()
> >   File "/home/ubuntu/op/telliot-feeds/src/telliot_feeds/reporters/interval.py", line 465, in report
> >     _, _ = await self.report_once()
> >   File "/home/ubuntu/op/telliot-feeds/src/telliot_feeds/reporters/interval.py", line 342, in report_once
> >     if not status.ok:
> > AttributeError: 'NoneType' object has no attribute 'ok'
> > ```
> 
> cmd to reproduce (on opt mainnet): `telliot report -a account -qt btc-usd-spot -p YOLO -wp 30`

for the same error or happened again? and is it only on mainnet?

**Comment by akremstudy** [comment]
think i might've found the line causing the break, will add a test

**Comment by oraclown** [comment]
@akremstudy All tests pass for me (either with the whole test run, or when run individually). Also, I fixed, skipped, or removed the interval reporter tests that were acting up. Could you double check on your end that everything looks good?

**Pull request merged**
