### PR TITLE
Only ask for block explorer & rpc urls

### LINKED ISSUE #579: when configuring endpoint via cli, only ask for node/rpc url
get rid of the prompts where it asks for provider and other stuff. just ask for url, simpler

### PR DESCRIPTION
**Pull request by oraclown**
### Summary

- Closes #579 

### Checklist

This pull request is:

- [ ] A documentation error, docs update, or typographical error fix
	- No tests or issue needed
- [ ] A code fix
	- Please reference the related issue by including "Closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a bug report issue 
	- Please include tests. Fixes without tests will not be accepted unless it's related to the documentation only.
    - Please make sure docs are updated if need be
- [x] A feature implementation
	- Please reference the related issue by including "Closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a feature enhancement issue 
	- Please include tests
    - Please make sure docs updates are both thorough and easy to reproduce by somebody with limited knowledge of the feature that you are submitting

**Happy engineering!**

### CODE REVIEW

**Review by tallywiesenberg — APPROVED** [review]
Very cool, this is a great change

**Comment by oraclown** [comment]
I removed `test_not_updating_settings` bc keeping the current settings is tested in `test_continue_with_incomplete_settings`.

**Comment by oraclown** [comment]
Still one failing:
`FAILED tests/utils/test_config_utils.py::test_update_all_configs - AssertionError: assert 10 > 15`

**Comment by tallywiesenberg** [comment]
> Still one failing: `FAILED tests/utils/test_config_utils.py::test_update_all_configs - AssertionError: assert 10 > 15`

I fixed this one, it was due to a weird nuance in config loading/saving!

**Comment by oraclown** [comment]
> > Still one failing: `FAILED tests/utils/test_config_utils.py::test_update_all_configs - AssertionError: assert 10 > 15`
> 
> I fixed this one, it was due to a weird nuance in config loading/saving!

Thanks, @tallywiesenberg !

**Pull request merged**
