### PR TITLE
Support EVMCall query type

### LINKED ISSUE #521: Support New Query Type -- [EVM Call]
- [x] Links to [dataSpecs](https://github.com/tellor-io/dataSpecs) issue & new query type file
- [x] Add query type (subclass `AbiQuery`)
- [x] Add sources (subclass `DataSource`)
- [x] Add feed (instance of `DataFeed`)
- [x] Add example instance of the query type to catalog
- [x] Add support for building custom instances of the new query type (using the `--build-feed` flag)
- [x] Tests for new query type, sources, feeds, & additions to the CLI
- [x] Update docs for each addition
- [ ] Include example transactions from a block explorer of new query type submitted to Tellor using `telliot-feeds`

### PR DESCRIPTION
**Pull request by oraclown**
### Summary

- Closes #521 
- **important:** This implementation includes [this proposed change for the dataSpec](https://github.com/tellor-io/dataSpecs/issues/107)

### Steps Taken to QA Changes

- Added source tests and an e2e test

### Checklist

This pull request is:

- [ ] A documentation error, docs update, or typographical error fix
	- No tests or issue needed
- [ ] A code fix
	- Please reference the related issue by including "Closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a bug report issue 
	- Please include tests. Fixes without tests will not be accepted unless it's related to the documentation only.
    - Please make sure docs are updated if need be
- [x] A feature implementation
	- Please reference the related issue by including "Closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a feature enhancement issue 
	- Please include tests
    - Please make sure docs updates are both thorough and easy to reproduce by somebody with limited knowledge of the feature that you are submitting

**Happy engineering!**

### CODE REVIEW

**Review by akremstudy — COMMENTED** [review]
Thanks @oraclown!
I have a few questions:
What happens if the request is to call a function that isn’t a getter? Will telliot break?
If there is a bad request won’t the reporter break out from telliot, for instance if a chain id that doesn’t exist?
Are you waiting to change the encoding when the dataspec is merged cause its still encoding the response once altogether?
This might be on my end, but tried reporting the example qt and couldn’t, does it work for you?
The build data feed isn’t working for me as well, works for you? maybe if you can add a test?

**Comment by oraclown** [comment]
`If there is a bad request won’t the reporter break out from telliot, for instance if a chain id that doesn’t exist?`
There's a catch-all for errors that happen within `get_response` (method of `EVMCallSource`), so I don't think so. But I added an example test that tips an EVMCall on a chain that we don't support.

**Comment by oraclown** [comment]
`Are you waiting to change the encoding when the dataspec is merged cause its still encoding the response once altogether?
This might be on my end, but tried reporting the example qt and couldn’t, does it work for you?`
- Fixed the example reporting part. Here's the command I used: `telliot report -a dev-acct-bags -qt evm-call-example -ncr`
- [submitValue tx](https://mumbai.polygonscan.com//tx/0x5324f9b4e2a15dfda4d9ef84733031a243f2152986132a5c1e439495ff940698) using above cmd
- The encoding seems to match the updated data spec (rsp encoded first, then encoded together with the timestamp it was called at). See decoded submit value below

Decoding the query data & submitted value works fine:
```console
(env) ➜  telliot-feeds git:(evm-call) telliot query decode -qd 0x00000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000745564d43616c6c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000000100000000000000000000000088df592f8eb5d7bd38bfef7deb0fbc02cf3778a00000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000000418160ddd00000000000000000000000000000000000000000000000000000000
Decoded query from data: EVMCall(chainId=1, contractAddress='0x88df592f8eb5d7bd38bfef7deb0fbc02cf3778a0', calldata=b'\x18\x16\r\xdd')
(env) ➜  telliot-feeds git:(evm-call) telliot query decode -svb 0x00000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000063e5570f00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000209ff91d8d6278fe5b1ec
Choose query type to decode submitted value:
[1] -- SpotPrice
[2] -- GasPriceOracle
...
[11] -- AmpleforthCustomSpotPrice
[12] -- EVMCall
Enter number from 1-12: 12
Your choice: EVMCall
Decoded value: (b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\t\xff\x91\xd8\xd6'\x8f\xe5\xb1\xec", 1675974415)

**Comment by oraclown** [comment]
still need to check these:
- [ ] `What happens if the request is to call a function that isn’t a getter? Will telliot break?`
- [ ] `The build data feed isn’t working for me as well, works for you? maybe if you can add a test?`

**Comment by oraclown** [comment]
> still need to check these:
> 
> * [ ]  `What happens if the request is to call a function that isn’t a getter? Will telliot break?`
> * [ ]  `The build data feed isn’t working for me as well, works for you? maybe if you can add a test?`

Able to reproduce build feed err:
```console
(env) ➜  telliot-feeds git:(evm-call) telliot report -a dev-acct-bags -ncr --build-feed
INFO    | telliot_core | telliot-core 0.1.9
INFO    | telliot_core | Connected to polygon-mumbai [default account: dev-acct-bags], time: 2023-02-09 21:30:15.275116
Your current settings...
Your chain id: 80001

Your mumbai endpoint: 
...
Proceed with current settings (y) or update (n)? [Y/n]: 
Keeping current settings...
Enter password for dev-acct-bags account: 
Choose query type:
01 -- AmpleforthCustomSpotPrice
02 -- AmpleforthUSPCE
03 -- DailyVolatility
04 -- DivaProtocol
05 -- EVMCall
06 -- GasPriceOracle
07 -- NumericApiManualResponse
08 -- NumericApiResponse
09 -- SnapshotOracle
10 -- SpotPrice
11 -- StringQuery
12 -- TWAP
13 -- TellorRNG
14 -- TellorRNGManualResponse
Enter number from 1-14: 5
Your choice: EVMCall
Enter value for QueryParameter chainId: 1
Enter value for QueryParameter contractAddress: 0x88dF592F8eb5D7Bd38bFeF7dEb0fBc02cf3778a0
Enter value for QueryParameter calldata: 0x18160ddd
ERROR   | telliot_core | Exception occurred in telliot-core app
ERROR   | telliot_core | <class 'TypeError'>
ERROR   | telliot_core | string argument without an encoding
ERROR   | telliot_core | ['  File "/Users/owen/tellor/telliot-feeds/src/telliot_feeds/cli/commands/report.py", line 363, in report\n    chosen_feed = build_feed_from_input()\n', '  File "/Users/owen/tellor/telliot-feeds/src/telliot_feeds/cli/utils.py", line 189, in build_feed_from_input\n    val = param_dtype(val)\n']
Traceback (most recent call last):
  File "/Users/owen/tellor/telliot-feeds/env/bin/telliot", line 33, in <module>
    sys.exit(load_entry_point('telliot-feeds', 'console_scripts', 'telliot')())
  File "/Users/owen/tellor/telliot-feeds/env/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/owen/tellor/telliot-feeds/env/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/owen/tellor/telliot-feeds/env/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/owen/tellor/telliot-feeds/env/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/owen/tellor/telliot-feeds/env/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/owen/tellor/telliot-feeds/env/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/owen/tellor/telliot-feeds/env/lib/python3.9/site-packages/telliot_core/cli/utils.py", line 18, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "/Users/owen/.pyenv/versions/3.9.7/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/owen/.pyenv/versions/3.9.7/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/owen/tellor/telliot-feeds/src/telliot_feeds/cli/commands/report.py", line 363, in report
    chosen_feed = build_feed_from_input()
  File "/Users/owen/tellor/telliot-feeds/src/telliot_feeds/cli/utils.py", line 189, in build_feed_from_input
    val = param_dtype(val)
TypeError: string argument without an encoding
```

**Comment by oraclown** [comment]
@akremstudy Added check for trying to call non getter functions & corresponding test

Lmk if these updates work fine for you

**Comment by akremstudy** [comment]
> @akremstudy Added check for trying to call non getter functions & corresponding test. I just hard-coded the gasPrice to 0
> 
> Lmk if these updates work fine for you

Nice, looks good to me. Thank you, @oraclown!

**Pull request merged**
